name: Deploy

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          node --version
          npm --version
          npm i

      - name: Build Site
        run: |
          npm run build
          touch build/.nojekyll
          echo "mrvauxs.net" > CNAME

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          folder: build
